### ISSUE TITLE
ModuleNotFoundError: No module named 'models.cycle_gan_model'

### ISSUE THREAD

**Issue by hhxdestiny** [tsingqguo/exposure-fusion-shadow-removal#11]
ModuleNotFoundError: No module named 'models.cycle_gan_model'

**Comment by Allen1119** [comment]
请问这个问题你解决了吗

**Comment by hhxdestiny** [comment]
@Allen1119 没有，作者的文档和工程对不上

**Comment by fl82hope** [comment]
Sorry, for the late reply.

Plese see the options/base_option.py, --model, please set this to Fusion or Refine. 

The code are based on cycle_gan, but we removed the cycle_gan_model. Then this error happen.
