### ISSUE TITLE
code for mask_threshold

### ISSUE THREAD

**Issue by BalinLin** [tsingqguo/exposure-fusion-shadow-removal#15]
Hello, could you provide the code you compute the shadow masks for inference time?
Thanks a lot.

**Comment by fl82hope** [comment]
Yes, we can provide them. I will upload them within these two days.

**Comment by BalinLin** [comment]
Thank you so much!!

**Comment by fl82hope** [comment]
Sorry for the late. 
https://github.com/fl82hope/exposure-fusion-shadow-removal/blob/patch-7/data_processing/test_mask_generation.py
code is here, please have a check.
