### ISSUE TITLE
在run eval.sh跟train.sh 都找不到SID_eval.py 跟 SID_train.py

### ISSUE THREAD

**Issue by qpaozixu** [tsingqguo/exposure-fusion-shadow-removal#18]

**Comment by fl82hope** [comment]
把SID改成OE就可以了。 新的pull没有merge，会尽快更新。

**Comment by qpaozixu** [comment]
請問測試用的 sh OE_test.sh 有放在git上嗎？

**Comment by fl82hope** [comment]
> 請問測試用的 sh OE_test.sh 有放在git上嗎？

直接使用OE_eval.sh，需要保证 Name参数，也就是保存Refine model weights的路径正确。
