### ISSUE TITLE
metric problem

### ISSUE THREAD

**Issue by Halfpoint1** [tsingqguo/exposure-fusion-shadow-removal#22]
I run eval.sh on ISTD+,but I get rmse : 6.285 | shadow_rmse : 9.934 | nonshadow_rmse : 4.958.

**Comment by fl82hope** [comment]
Hello,  for the evalution, the matlab code is more accurate, many works adopted it for comparision.

The eval.sh calls our implemented python-version evaluation code, which is not accurate enough. Please have a try for the matlab version, which is provdied in the ReadMe.

**Comment by fl82hope** [comment]
https://drive.google.com/file/d/1SAMqLy3dSONPgeC5ZQskPoeq60FEx9Vk/view?usp=sharing
you can use this code for evaluation. I just updated it in the ReadME, not merge to the main branch yet.

**Comment by cvbird** [comment]
Hi, Thanks for sharing the evaluation code. However, I found all inputs were resize to (256, 256) while the ground truth shadow free image is of shape (640, 480). I wonder whether this implementation is consistent with other papers ?  thank you.
