### ISSUE TITLE
Why divide here by 2 and add 0.5?

### ISSUE THREAD

**Issue by sicong-li** [tsingqguo/exposure-fusion-shadow-removal#28]
Great work. And I have a question : Why divide here by 2 and add 0.5? https://github.com/tsingqguo/exposure-fusion-shadow-removal/blob/main/models/Refine_model.py#L206

**Comment by fl82hope** [comment]
This is beacuse change the value to [0,1], the out from self.input_img, shadow_output  ( both in range [-1,1] ).
