### ISSUE TITLE
Error when switching to test mode during training

### ISSUE THREAD

**Issue by yx-chan131** [tsingqguo/exposure-fusion-shadow-removal#29]
Hi, @xuhangc I encounter the same problem as you. May I know how you fix this problem? 
As @yuhaoliu7456 suggested, I did write an if statement to skip input['param'] during the test. 
```python
if 'param' in input:  #input['param] does not exist during the test
        self.shadow_param = input['param'].to(self.device).type(torch.float)
```
However, I found that variable self.shadow_param will be used in forward method.
```python
addgt = self.shadow_param[:, [0, 2, 4]]
mulgt = self.shadow_param[:, [1, 3, 5]]
```
Therefore I still encounter error when switching to test mode during training.
![error](https://user-images.githubusercontent.com/68681893/139272502-a05e2313-d6f7-4db5-9c4f-7bbf8a7eef95.JPG)

_Originally posted by @yx-chan131 in https://github.com/tsingqguo/exposure-fusion-shadow-removal/issues/27#issuecomment-953880303_

**Comment by fl82hope** [comment]
Hi, this addgt and mulgt are not used later, you can annotate it.

**Comment by yx-chan131** [comment]
@fl82hope Hi, thanks for your prompt reply. To be more clear, did you mean that the variables addgt and mulgt are the same as input['param'] which will not be used during testing mode?

Thanks!

**Comment by fl82hope** [comment]
> @fl82hope Hi, thanks for your prompt reply. To be more clear, did you mean that the variables addgt and mulgt are the same as input['param'] which will not be used during testing mode?
> 
> Thanks!

Yes, exactly.

**Comment by xuhangc** [comment]
I change self.shadow_param to shadow_param_pred depending on the flag of training state and the code works. But somehow the result will turn out to be very bad. I suppose there should be another better solution.

**Comment by dante1024** [comment]
> @fl82hope Hi, thanks for your prompt reply. To be more clear, did you mean that the variables addgt and mulgt are the same as input['param'] which will not be used during testing mode?
> 
> Thanks!

I also encountered the same problem as you, how do you modify Fusion_model.py to make it run normally?
