### ISSUE TITLE
Having a problem while loading pre-trained weights.

### ISSUE THREAD

**Issue by yakhyo** [tsingqguo/exposure-fusion-shadow-removal#31]
I downloaded pre-trained weights from the link provided in this repo. while loading the weights there is something wrong in weight `latest_net_R.pth`.

```
Traceback (most recent call last):
  File "/home/divus/Projects/Git/exposure-fusion-shadow-removal/OE_eval.py", line 33, in <module>
    model.setup(opt)
  File "/home/divus/Projects/Git/exposure-fusion-shadow-removal/models/base_model.py", line 84, in setup
    self.load_networks(opt.epoch)
  File "/home/divus/Projects/Git/exposure-fusion-shadow-removal/models/base_model.py", line 198, in load_networks
    net.load_state_dict(state_dict)
  File "/home/divus/Python/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UnetGenerator:
	size mismatch for model.model.0.weight: copying a param with shape torch.Size([64, 19, 4, 4]) from checkpoint, the shape in current model is torch.Size([64, 13, 4, 4]).
	size mismatch for model.model.3.weight: copying a param with shape torch.Size([128, 486, 4, 4]) from checkpoint, the shape in current model is torch.Size([128, 324, 4, 4]).
	size mismatch for model.model.3.bias: copying a param with shape torch.Size([486]) from checkpoint, the shape in current model is torch.Size([324]).
```

**Comment by fl82hope** [comment]
Please check the model input of modeM, 
self.netM = networks.define_G(1 + 3 + n * 3, ((1 + n) * 3) * 3 * ks * ks, opt.ngf, 'unet_256', opt.norm,
                                      not opt.no_dropout, opt.init_type, opt.init_gain, self.gpu_ids)
"
torch.Size([64, 19, 4, 4]) from checkpoint, the shape in current model is torch.Size([64, 13, 4, 4]).
"
here n shoud be = 5.

**Comment by yakhyo** [comment]
Thanks for your reply, I changed it as you mentioned but now started occurring other errors:
1. `self.shadow_param = input['param'].to(self.device).type(torch.float) KeyError: 'param'`. Then I commented out that line according to this discussion: https://github.com/tsingqguo/exposure-fusion-shadow-removal/issues/27
2. After running I got this error:  `    
addgt = self.shadow_param[:, [0, 2, 4]]
AttributeError: 'FusionModel' object has no attribute 'shadow_param'`. Then according to this -> https://github.com/tsingqguo/exposure-fusion-shadow-removal/issues/29  discussion
I commented out **addgt** and **mulgt**, however then having following problem
![Screenshot from 2021-11-22 16-15-05](https://user-images.githubusercontent.com/28424328/142819222-47e8bdb5-d304-40cc-bf28-251644738992.png)
:
If this code no longer using cycleGAN could you update the code and make it work with Fusion model or Refine model.
Thanks in advance @fl82hope

**Comment by yakhyo** [comment]
I used **Refine** model then this error disappeared but still this problem exists with **Refine model**: https://github.com/tsingqguo/exposure-fusion-shadow-removal/issues/33
