### ISSUE TITLE
How can I inference the model against a single image?

### ISSUE THREAD

**Issue by yakhyo** [tsingqguo/exposure-fusion-shadow-removal#34]
After seeing this issue https://github.com/tsingqguo/exposure-fusion-shadow-removal/issues/14, Now I am wondering is it possible to inference the model against a single image? Or do we need to give a paired image always? Shadow image and shadow mask for test.
Thanks in advance.

**Comment by Season-Chan** [comment]
Accroding to the paper, shadow image and corresponding shadow mask are required for testing.
