### ISSUE TITLE
测试集评价指标用的是否为mae

### ISSUE THREAD

**Issue by xzltc** [tsingqguo/exposure-fusion-shadow-removal#38]
Hi，您好！看到SID那边[https://github.com/cvlab-stonybrook/SID](url)指出了之前项目很多用的都是MAE而不是RMSE最为评价指标。
您项目里OE_eval.py中也能看到rmse计算的代码，但是被注掉了，所以最后采用的其实还是计算MAE得到评价指标吗？

**Comment by fl82hope** [comment]
是的，实际用的metric是MAE，我们的评价代码也是从SID作者那里来的。
