### ISSUE TITLE
train

### ISSUE THREAD

**Issue by kkllww** [tsingqguo/exposure-fusion-shadow-removal#46]
when i                sh OE_train.sh
this happend

switching to testing mode
Traceback (most recent call last):
  File "./OE_train.py", line 123, in <module>
    model.set_input(data)
  File "/mnt/data/konglingwei/exposure-fusion-shadow-removal-main/models/Fusion_model.py", line 170, in set_input
    self.shadow_param = input['param'].to(self.device).type(torch.float)
KeyError: 'param'

**Comment by yuanyufang** [comment]
这个需要改一下代码，你留一下邮箱  我可以发你

**Comment by xuhangc** [comment]
@yuanyufang

yc17491@umac.mo
Thank you in advance.

**Comment by kkllww** [comment]
> 

1715005876@qq.com，谢谢你，还想问你一下，在训练Refine之后你会出现这样的情况吗。
![image](https://user-images.githubusercontent.com/90187836/175065949-bc247360-2e7f-4eda-aece-95816c487a62.png)

**Comment by kkllww** [comment]
> 这个需要改一下代码，你留一下邮箱 我可以发你

1715005876@qq.com
谢谢你，还想问你一下，在训练Refine之后你会出现这样的情况吗。
![image](https://user-images.githubusercontent.com/90187836/175066358-dcc3e33b-be23-4cf1-8d16-faa8701f6d56.png)

**Comment by yjwnet9** [comment]
@yuanyufang
Can you send it to me, too?
yjwnet99@gmail.com

**Comment by Rookie1121** [comment]
> 这个需要改一下代码，你留一下邮箱 我可以发你
我也遇到了这个问题，请问可以发一份给我吗？
1152073423@qq.com

**Comment by Rookie1121** [comment]
@yuanyufang 
我也遇到了这个问题，请问可以发一份给我吗？
1152073423@qq.com

**Comment by xuhangc** [comment]
> 我也遇到了这个问题，请问可以发一份给我吗？

可以试试我的

https://github.com/CV-Reimplementation/AEFNet-Reimplementation

**Comment by Rookie1121** [comment]
> > 我也遇到了这个问题，请问可以发一份给我吗？
> 
> 可以试试我的
> 
> https://github.com/CV-Reimplementation/AEFNet-Reimplementation

感谢您的帮助
