### ISSUE TITLE
Where can i find the algorithm to calculate the GT of alpha and beta?  can you explain it here？

### ISSUE THREAD

**Issue by zhuyr97** [tsingqguo/exposure-fusion-shadow-removal#5]

**Comment by JunrQ** [comment]
https://github.com/cvlab-stonybrook/SID/blob/main/data_processing/compute_params.ipynb

**Comment by fl82hope** [comment]
Inside the data_procesing folder, you can obtain the ground truth by running compute_params.ipynb.
